package ctrmap.editor.gui.editors.gen5.items;

import ctrmap.editor.gui.editors.common.AbstractTabbedEditor;
import ctrmap.editor.gui.editors.util.UserEnumHandler;
import ctrmap.formats.pokemon.gen5.battle.trainer.WBTrainerData;
import ctrmap.formats.pokemon.gen5.battle.trainer.WBTrainerPoke;
import ctrmap.formats.pokemon.gen5.items.WBItemBattleStats;
import ctrmap.formats.pokemon.gen5.items.WBItemData;
import xstandard.formats.yaml.Yaml;
import xstandard.formats.yaml.YamlNode;

public class VItemEditor extends javax.swing.JPanel implements AbstractTabbedEditor {
    public VItemEditor() {
        initComponents();
    }

    public WBItemData LoadEntryViaYml(Yaml yml) {
        WBItemData itemData = new WBItemData();
        WBItemBattleStats stats = new WBItemBattleStats();

        return itemData;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileLoadPanel = new javax.swing.JPanel();
        btnOpenScrInIDE22 = new javax.swing.JButton();
        btnAddZoneData = new javax.swing.JButton();
        trainerSelector = new xstandard.gui.components.combobox.ComboBoxAndSpinner();
        jItemTabbed = new javax.swing.JTabbedPane();

        fileLoadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));

        btnOpenScrInIDE22.setText("Open Item");
        btnOpenScrInIDE22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenScrInIDE22ActionPerformed(evt);
            }
        });

        btnAddZoneData.setText("+");
        btnAddZoneData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddZoneDataActionPerformed(evt);
            }
        });

        trainerSelector.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        trainerSelector.setMaximumRowCount(35);

        javax.swing.GroupLayout fileLoadPanelLayout = new javax.swing.GroupLayout(fileLoadPanel);
        fileLoadPanel.setLayout(fileLoadPanelLayout);
        fileLoadPanelLayout.setHorizontalGroup(
            fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddZoneData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenScrInIDE22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(647, Short.MAX_VALUE))
        );
        fileLoadPanelLayout.setVerticalGroup(
            fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadPanelLayout.createSequentialGroup()
                .addGroup(fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpenScrInIDE22)
                        .addComponent(btnAddZoneData))
                    .addComponent(trainerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jItemTabbed)
                    .addComponent(fileLoadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jItemTabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenScrInIDE22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenScrInIDE22ActionPerformed

    }//GEN-LAST:event_btnOpenScrInIDE22ActionPerformed

    private void btnAddZoneDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddZoneDataActionPerformed

    }//GEN-LAST:event_btnAddZoneDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddZoneData;
    private javax.swing.JButton btnOpenScrInIDE22;
    private javax.swing.JPanel fileLoadPanel;
    private javax.swing.JTabbedPane jItemTabbed;
    private xstandard.gui.components.combobox.ComboBoxAndSpinner trainerSelector;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabName() {
        return "Item Editor";
    }
}
