package ctrmap.formats.pokemon.gen5.pml;

/**
 *
 * @author Hibiki
 */
public enum WBPMLLevelUpMoveNames {
    MOVE_NONE("None"),
    MOVE_POUND("Pound"),
    MOVE_KARATE_CHOP("Karate Chop"),
    MOVE_DOUBLESLAP("DoubleSlap"),
    MOVE_COMET_PUNCH("Comet Punch"),
    MOVE_MEGA_PUNCH("Mega Punch"),
    MOVE_PAY_DAY("Pay Day"),
    MOVE_FIRE_PUNCH("Fire Punch"),
    MOVE_ICE_PUNCH("Ice Punch"),
    MOVE_THUNDERPUNCH("ThunderPunch"),
    MOVE_SCRATCH("Scratch"),
    MOVE_VICEGRIP("ViceGrip"),
    MOVE_GUILLOTINE("Guillotine"),
    MOVE_RAZOR_WIND("Razor Wind"),
    MOVE_SWORDS_DANCE("Swords Dance"),
    MOVE_CUT("Cut"),
    MOVE_GUST("Gust"),
    MOVE_WING_ATTACK("Wing Attack"),
    MOVE_WHIRLWIND("Whirlwind"),
    MOVE_FLY("Fly"),
    MOVE_BIND("Bind"),
    MOVE_SLAM("Slam"),
    MOVE_VINE_WHIP("Vine Whip"),
    MOVE_STOMP("Stomp"),
    MOVE_DOUBLE_KICK("Double Kick"),
    MOVE_MEGA_KICK("Mega Kick"),
    MOVE_JUMP_KICK("Jump Kick"),
    MOVE_ROLLING_KICK("Rolling Kick"),
    MOVE_SANDATTACK("Sand-Attack"),
    MOVE_HEADBUTT("Headbutt"),
    MOVE_HORN_ATTACK("Horn Attack"),
    MOVE_FURY_ATTACK("Fury Attack"),
    MOVE_HORN_DRILL("Horn Drill"),
    MOVE_TACKLE("Tackle"),
    MOVE_BODY_SLAM("Body Slam"),
    MOVE_WRAP("Wrap"),
    MOVE_TAKE_DOWN("Take Down"),
    MOVE_THRASH("Thrash"),
    MOVE_DOUBLEEDGE("Double-Edge"),
    MOVE_TAIL_WHIP("Tail Whip"),
    MOVE_POISON_STING("Poison Sting"),
    MOVE_TWINEEDLE("Twineedle"),
    MOVE_PIN_MISSILE("Pin Missile"),
    MOVE_LEER("Leer"),
    MOVE_BITE("Bite"),
    MOVE_GROWL("Growl"),
    MOVE_ROAR("Roar"),
    MOVE_SING("Sing"),
    MOVE_SUPERSONIC("Supersonic"),
    MOVE_SONICBOOM("SonicBoom"),
    MOVE_DISABLE("Disable"),
    MOVE_ACID("Acid"),
    MOVE_EMBER("Ember"),
    MOVE_FLAMETHROWER("Flamethrower"),
    MOVE_MIST("Mist"),
    MOVE_WATER_GUN("Water Gun"),
    MOVE_HYDRO_PUMP("Hydro Pump"),
    MOVE_SURF("Surf"),
    MOVE_ICE_BEAM("Ice Beam"),
    MOVE_BLIZZARD("Blizzard"),
    MOVE_PSYBEAM("Psybeam"),
    MOVE_BUBBLEBEAM("BubbleBeam"),
    MOVE_AURORA_BEAM("Aurora Beam"),
    MOVE_HYPER_BEAM("Hyper Beam"),
    MOVE_PECK("Peck"),
    MOVE_DRILL_PECK("Drill Peck"),
    MOVE_SUBMISSION("Submission"),
    MOVE_LOW_KICK("Low Kick"),
    MOVE_COUNTER("Counter"),
    MOVE_SEISMIC_TOSS("Seismic Toss"),
    MOVE_STRENGTH("Strength"),
    MOVE_ABSORB("Absorb"),
    MOVE_MEGA_DRAIN("Mega Drain"),
    MOVE_LEECH_SEED("Leech Seed"),
    MOVE_GROWTH("Growth"),
    MOVE_RAZOR_LEAF("Razor Leaf"),
    MOVE_SOLARBEAM("SolarBeam"),
    MOVE_POISONPOWDER("PoisonPowder"),
    MOVE_STUN_SPORE("Stun Spore"),
    MOVE_SLEEP_POWDER("Sleep Powder"),
    MOVE_PETAL_DANCE("Petal Dance"),
    MOVE_STRING_SHOT("String Shot"),
    MOVE_DRAGON_RAGE("Dragon Rage"),
    MOVE_FIRE_SPIN("Fire Spin"),
    MOVE_THUNDERSHOCK("ThunderShock"),
    MOVE_THUNDERBOLT("Thunderbolt"),
    MOVE_THUNDER_WAVE("Thunder Wave"),
    MOVE_THUNDER("Thunder"),
    MOVE_ROCK_THROW("Rock Throw"),
    MOVE_EARTHQUAKE("Earthquake"),
    MOVE_FISSURE("Fissure"),
    MOVE_DIG("Dig"),
    MOVE_TOXIC("Toxic"),
    MOVE_CONFUSION("Confusion"),
    MOVE_PSYCHIC("Psychic"),
    MOVE_HYPNOSIS("Hypnosis"),
    MOVE_MEDITATE("Meditate"),
    MOVE_AGILITY("Agility"),
    MOVE_QUICK_ATTACK("Quick Attack"),
    MOVE_RAGE("Rage"),
    MOVE_TELEPORT("Teleport"),
    MOVE_NIGHT_SHADE("Night Shade"),
    MOVE_MIMIC("Mimic"),
    MOVE_SCREECH("Screech"),
    MOVE_DOUBLE_TEAM("Double Team"),
    MOVE_RECOVER("Recover"),
    MOVE_HARDEN("Harden"),
    MOVE_MINIMIZE("Minimize"),
    MOVE_SMOKESCREEN("SmokeScreen"),
    MOVE_CONFUSE_RAY("Confuse Ray"),
    MOVE_WITHDRAW("Withdraw"),
    MOVE_DEFENSE_CURL("Defense Curl"),
    MOVE_BARRIER("Barrier"),
    MOVE_LIGHT_SCREEN("Light Screen"),
    MOVE_HAZE("Haze"),
    MOVE_REFLECT("Reflect"),
    MOVE_FOCUS_ENERGY("Focus Energy"),
    MOVE_BIDE("Bide"),
    MOVE_METRONOME("Metronome"),
    MOVE_MIRROR_MOVE("Mirror Move"),
    MOVE_SELFDESTRUCT("Selfdestruct"),
    MOVE_EGG_BOMB("Egg Bomb"),
    MOVE_LICK("Lick"),
    MOVE_SMOG("Smog"),
    MOVE_SLUDGE("Sludge"),
    MOVE_BONE_CLUB("Bone Club"),
    MOVE_FIRE_BLAST("Fire Blast"),
    MOVE_WATERFALL("Waterfall"),
    MOVE_CLAMP("Clamp"),
    MOVE_SWIFT("Swift"),
    MOVE_SKULL_BASH("Skull Bash"),
    MOVE_SPIKE_CANNON("Spike Cannon"),
    MOVE_CONSTRICT("Constrict"),
    MOVE_AMNESIA("Amnesia"),
    MOVE_KINESIS("Kinesis"),
    MOVE_SOFTBOILED("Softboiled"),
    MOVE_HI_JUMP_KICK("Hi Jump Kick"),
    MOVE_GLARE("Glare"),
    MOVE_DREAM_EATER("Dream Eater"),
    MOVE_POISON_GAS("Poison Gas"),
    MOVE_BARRAGE("Barrage"),
    MOVE_LEECH_LIFE("Leech Life"),
    MOVE_LOVELY_KISS("Lovely Kiss"),
    MOVE_SKY_ATTACK("Sky Attack"),
    MOVE_TRANSFORM("Transform"),
    MOVE_BUBBLE("Bubble"),
    MOVE_DIZZY_PUNCH("Dizzy Punch"),
    MOVE_SPORE("Spore"),
    MOVE_FLASH("Flash"),
    MOVE_PSYWAVE("Psywave"),
    MOVE_SPLASH("Splash"),
    MOVE_ACID_ARMOR("Acid Armor"),
    MOVE_CRABHAMMER("Crabhammer"),
    MOVE_EXPLOSION("Explosion"),
    MOVE_FURY_SWIPES("Fury Swipes"),
    MOVE_BONEMERANG("Bonemerang"),
    MOVE_REST("Rest"),
    MOVE_ROCK_SLIDE("Rock Slide"),
    MOVE_HYPER_FANG("Hyper Fang"),
    MOVE_SHARPEN("Sharpen"),
    MOVE_CONVERSION("Conversion"),
    MOVE_TRI_ATTACK("Tri Attack"),
    MOVE_SUPER_FANG("Super Fang"),
    MOVE_SLASH("Slash"),
    MOVE_SUBSTITUTE("Substitute"),
    MOVE_STRUGGLE("Struggle"),
    MOVE_SKETCH("Sketch"),
    MOVE_TRIPLE_KICK("Triple Kick"),
    MOVE_THIEF("Thief"),
    MOVE_SPIDER_WEB("Spider Web"),
    MOVE_MIND_READER("Mind Reader"),
    MOVE_NIGHTMARE("Nightmare"),
    MOVE_FLAME_WHEEL("Flame Wheel"),
    MOVE_SNORE("Snore"),
    MOVE_CURSE("Curse"),
    MOVE_FLAIL("Flail"),
    MOVE_CONVERSION_2("Conversion 2"),
    MOVE_AEROBLAST("Aeroblast"),
    MOVE_COTTON_SPORE("Cotton Spore"),
    MOVE_REVERSAL("Reversal"),
    MOVE_SPITE("Spite"),
    MOVE_POWDER_SNOW("Powder Snow"),
    MOVE_PROTECT("Protect"),
    MOVE_MACH_PUNCH("Mach Punch"),
    MOVE_SCARY_FACE("Scary Face"),
    MOVE_FAINT_ATTACK("Faint Attack"),
    MOVE_SWEET_KISS("Sweet Kiss"),
    MOVE_BELLY_DRUM("Belly Drum"),
    MOVE_SLUDGE_BOMB("Sludge Bomb"),
    MOVE_MUDSLAP("Mud-Slap"),
    MOVE_OCTAZOOKA("Octazooka"),
    MOVE_SPIKES("Spikes"),
    MOVE_ZAP_CANNON("Zap Cannon"),
    MOVE_FORESIGHT("Foresight"),
    MOVE_DESTINY_BOND("Destiny Bond"),
    MOVE_PERISH_SONG("Perish Song"),
    MOVE_ICY_WIND("Icy Wind"),
    MOVE_DETECT("Detect"),
    MOVE_BONE_RUSH("Bone Rush"),
    MOVE_LOCKON("Lock-On"),
    MOVE_OUTRAGE("Outrage"),
    MOVE_SANDSTORM("Sandstorm"),
    MOVE_GIGA_DRAIN("Giga Drain"),
    MOVE_ENDURE("Endure"),
    MOVE_CHARM("Charm"),
    MOVE_ROLLOUT("Rollout"),
    MOVE_FALSE_SWIPE("False Swipe"),
    MOVE_SWAGGER("Swagger"),
    MOVE_MILK_DRINK("Milk Drink"),
    MOVE_SPARK("Spark"),
    MOVE_FURY_CUTTER("Fury Cutter"),
    MOVE_STEEL_WING("Steel Wing"),
    MOVE_MEAN_LOOK("Mean Look"),
    MOVE_ATTRACT("Attract"),
    MOVE_SLEEP_TALK("Sleep Talk"),
    MOVE_HEAL_BELL("Heal Bell"),
    MOVE_RETURN("Return"),
    MOVE_PRESENT("Present"),
    MOVE_FRUSTRATION("Frustration"),
    MOVE_SAFEGUARD("Safeguard"),
    MOVE_PAIN_SPLIT("Pain Split"),
    MOVE_SACRED_FIRE("Sacred Fire"),
    MOVE_MAGNITUDE("Magnitude"),
    MOVE_DYNAMICPUNCH("DynamicPunch"),
    MOVE_MEGAHORN("Megahorn"),
    MOVE_DRAGONBREATH("DragonBreath"),
    MOVE_BATON_PASS("Baton Pass"),
    MOVE_ENCORE("Encore"),
    MOVE_PURSUIT("Pursuit"),
    MOVE_RAPID_SPIN("Rapid Spin"),
    MOVE_SWEET_SCENT("Sweet Scent"),
    MOVE_IRON_TAIL("Iron Tail"),
    MOVE_METAL_CLAW("Metal Claw"),
    MOVE_VITAL_THROW("Vital Throw"),
    MOVE_MORNING_SUN("Morning Sun"),
    MOVE_SYNTHESIS("Synthesis"),
    MOVE_MOONLIGHT("Moonlight"),
    MOVE_HIDDEN_POWER("Hidden Power"),
    MOVE_CROSS_CHOP("Cross Chop"),
    MOVE_TWISTER("Twister"),
    MOVE_RAIN_DANCE("Rain Dance"),
    MOVE_SUNNY_DAY("Sunny Day"),
    MOVE_CRUNCH("Crunch"),
    MOVE_MIRROR_COAT("Mirror Coat"),
    MOVE_PSYCH_UP("Psych Up"),
    MOVE_EXTREMESPEED("ExtremeSpeed"),
    MOVE_ANCIENTPOWER("AncientPower"),
    MOVE_SHADOW_BALL("Shadow Ball"),
    MOVE_FUTURE_SIGHT("Future Sight"),
    MOVE_ROCK_SMASH("Rock Smash"),
    MOVE_WHIRLPOOL("Whirlpool"),
    MOVE_BEAT_UP("Beat Up"),
    MOVE_FAKE_OUT("Fake Out"),
    MOVE_UPROAR("Uproar"),
    MOVE_STOCKPILE("Stockpile"),
    MOVE_SPIT_UP("Spit Up"),
    MOVE_SWALLOW("Swallow"),
    MOVE_HEAT_WAVE("Heat Wave"),
    MOVE_HAIL("Hail"),
    MOVE_TORMENT("Torment"),
    MOVE_FLATTER("Flatter"),
    MOVE_WILLOWISP("Will-O-Wisp"),
    MOVE_MEMENTO("Memento"),
    MOVE_FACADE("Facade"),
    MOVE_FOCUS_PUNCH("Focus Punch"),
    MOVE_SMELLINGSALT("SmellingSalt"),
    MOVE_FOLLOW_ME("Follow Me"),
    MOVE_NATURE_POWER("Nature Power"),
    MOVE_CHARGE("Charge"),
    MOVE_TAUNT("Taunt"),
    MOVE_HELPING_HAND("Helping Hand"),
    MOVE_TRICK("Trick"),
    MOVE_ROLE_PLAY("Role Play"),
    MOVE_WISH("Wish"),
    MOVE_ASSIST("Assist"),
    MOVE_INGRAIN("Ingrain"),
    MOVE_SUPERPOWER("Superpower"),
    MOVE_MAGIC_COAT("Magic Coat"),
    MOVE_RECYCLE("Recycle"),
    MOVE_REVENGE("Revenge"),
    MOVE_BRICK_BREAK("Brick Break"),
    MOVE_YAWN("Yawn"),
    MOVE_KNOCK_OFF("Knock Off"),
    MOVE_ENDEAVOR("Endeavor"),
    MOVE_ERUPTION("Eruption"),
    MOVE_SKILL_SWAP("Skill Swap"),
    MOVE_IMPRISON("Imprison"),
    MOVE_REFRESH("Refresh"),
    MOVE_GRUDGE("Grudge"),
    MOVE_SNATCH("Snatch"),
    MOVE_SECRET_POWER("Secret Power"),
    MOVE_DIVE("Dive"),
    MOVE_ARM_THRUST("Arm Thrust"),
    MOVE_CAMOUFLAGE("Camouflage"),
    MOVE_TAIL_GLOW("Tail Glow"),
    MOVE_LUSTER_PURGE("Luster Purge"),
    MOVE_MIST_BALL("Mist Ball"),
    MOVE_FEATHERDANCE("FeatherDance"),
    MOVE_TEETER_DANCE("Teeter Dance"),
    MOVE_BLAZE_KICK("Blaze Kick"),
    MOVE_MUD_SPORT("Mud Sport"),
    MOVE_ICE_BALL("Ice Ball"),
    MOVE_NEEDLE_ARM("Needle Arm"),
    MOVE_SLACK_OFF("Slack Off"),
    MOVE_HYPER_VOICE("Hyper Voice"),
    MOVE_POISON_FANG("Poison Fang"),
    MOVE_CRUSH_CLAW("Crush Claw"),
    MOVE_BLAST_BURN("Blast Burn"),
    MOVE_HYDRO_CANNON("Hydro Cannon"),
    MOVE_METEOR_MASH("Meteor Mash"),
    MOVE_ASTONISH("Astonish"),
    MOVE_WEATHER_BALL("Weather Ball"),
    MOVE_AROMATHERAPY("Aromatherapy"),
    MOVE_FAKE_TEARS("Fake Tears"),
    MOVE_AIR_CUTTER("Air Cutter"),
    MOVE_OVERHEAT("Overheat"),
    MOVE_ODOR_SLEUTH("Odor Sleuth"),
    MOVE_ROCK_TOMB("Rock Tomb"),
    MOVE_SILVER_WIND("Silver Wind"),
    MOVE_METAL_SOUND("Metal Sound"),
    MOVE_GRASSWHISTLE("GrassWhistle"),
    MOVE_TICKLE("Tickle"),
    MOVE_COSMIC_POWER("Cosmic Power"),
    MOVE_WATER_SPOUT("Water Spout"),
    MOVE_SIGNAL_BEAM("Signal Beam"),
    MOVE_SHADOW_PUNCH("Shadow Punch"),
    MOVE_EXTRASENSORY("Extrasensory"),
    MOVE_SKY_UPPERCUT("Sky Uppercut"),
    MOVE_SAND_TOMB("Sand Tomb"),
    MOVE_SHEER_COLD("Sheer Cold"),
    MOVE_MUDDY_WATER("Muddy Water"),
    MOVE_BULLET_SEED("Bullet Seed"),
    MOVE_AERIAL_ACE("Aerial Ace"),
    MOVE_ICICLE_SPEAR("Icicle Spear"),
    MOVE_IRON_DEFENSE("Iron Defense"),
    MOVE_BLOCK("Block"),
    MOVE_HOWL("Howl"),
    MOVE_DRAGON_CLAW("Dragon Claw"),
    MOVE_FRENZY_PLANT("Frenzy Plant"),
    MOVE_BULK_UP("Bulk Up"),
    MOVE_BOUNCE("Bounce"),
    MOVE_MUD_SHOT("Mud Shot"),
    MOVE_POISON_TAIL("Poison Tail"),
    MOVE_COVET("Covet"),
    MOVE_VOLT_TACKLE("Volt Tackle"),
    MOVE_MAGICAL_LEAF("Magical Leaf"),
    MOVE_WATER_SPORT("Water Sport"),
    MOVE_CALM_MIND("Calm Mind"),
    MOVE_LEAF_BLADE("Leaf Blade"),
    MOVE_DRAGON_DANCE("Dragon Dance"),
    MOVE_ROCK_BLAST("Rock Blast"),
    MOVE_SHOCK_WAVE("Shock Wave"),
    MOVE_WATER_PULSE("Water Pulse"),
    MOVE_DOOM_DESIRE("Doom Desire"),
    MOVE_PSYCHO_BOOST("Psycho Boost"),
    MOVE_ROOST("Roost"),
    MOVE_GRAVITY("Gravity"),
    MOVE_MIRACLE_EYE("Miracle Eye"),
    MOVE_WAKEUP_SLAP("Wake-Up Slap"),
    MOVE_HAMMER_ARM("Hammer Arm"),
    MOVE_GYRO_BALL("Gyro Ball"),
    MOVE_HEALING_WISH("Healing Wish"),
    MOVE_BRINE("Brine"),
    MOVE_NATURAL_GIFT("Natural Gift"),
    MOVE_FEINT("Feint"),
    MOVE_PLUCK("Pluck"),
    MOVE_TAILWIND("Tailwind"),
    MOVE_ACUPRESSURE("Acupressure"),
    MOVE_METAL_BURST("Metal Burst"),
    MOVE_UTURN("U-turn"),
    MOVE_CLOSE_COMBAT("Close Combat"),
    MOVE_PAYBACK("Payback"),
    MOVE_ASSURANCE("Assurance"),
    MOVE_EMBARGO("Embargo"),
    MOVE_FLING("Fling"),
    MOVE_PSYCHO_SHIFT("Psycho Shift"),
    MOVE_TRUMP_CARD("Trump Card"),
    MOVE_HEAL_BLOCK("Heal Block"),
    MOVE_WRING_OUT("Wring Out"),
    MOVE_POWER_TRICK("Power Trick"),
    MOVE_GASTRO_ACID("Gastro Acid"),
    MOVE_LUCKY_CHANT("Lucky Chant"),
    MOVE_ME_FIRST("Me First"),
    MOVE_COPYCAT("Copycat"),
    MOVE_POWER_SWAP("Power Swap"),
    MOVE_GUARD_SWAP("Guard Swap"),
    MOVE_PUNISHMENT("Punishment"),
    MOVE_LAST_RESORT("Last Resort"),
    MOVE_WORRY_SEED("Worry Seed"),
    MOVE_SUCKER_PUNCH("Sucker Punch"),
    MOVE_TOXIC_SPIKES("Toxic Spikes"),
    MOVE_HEART_SWAP("Heart Swap"),
    MOVE_AQUA_RING("Aqua Ring"),
    MOVE_MAGNET_RISE("Magnet Rise"),
    MOVE_FLARE_BLITZ("Flare Blitz"),
    MOVE_FORCE_PALM("Force Palm"),
    MOVE_AURA_SPHERE("Aura Sphere"),
    MOVE_ROCK_POLISH("Rock Polish"),
    MOVE_POISON_JAB("Poison Jab"),
    MOVE_DARK_PULSE("Dark Pulse"),
    MOVE_NIGHT_SLASH("Night Slash"),
    MOVE_AQUA_TAIL("Aqua Tail"),
    MOVE_SEED_BOMB("Seed Bomb"),
    MOVE_AIR_SLASH("Air Slash"),
    MOVE_XSCISSOR("X-Scissor"),
    MOVE_BUG_BUZZ("Bug Buzz"),
    MOVE_DRAGON_PULSE("Dragon Pulse"),
    MOVE_DRAGON_RUSH("Dragon Rush"),
    MOVE_POWER_GEM("Power Gem"),
    MOVE_DRAIN_PUNCH("Drain Punch"),
    MOVE_VACUUM_WAVE("Vacuum Wave"),
    MOVE_FOCUS_BLAST("Focus Blast"),
    MOVE_ENERGY_BALL("Energy Ball"),
    MOVE_BRAVE_BIRD("Brave Bird"),
    MOVE_EARTH_POWER("Earth Power"),
    MOVE_SWITCHEROO("Switcheroo"),
    MOVE_GIGA_IMPACT("Giga Impact"),
    MOVE_NASTY_PLOT("Nasty Plot"),
    MOVE_BULLET_PUNCH("Bullet Punch"),
    MOVE_AVALANCHE("Avalanche"),
    MOVE_ICE_SHARD("Ice Shard"),
    MOVE_SHADOW_CLAW("Shadow Claw"),
    MOVE_THUNDER_FANG("Thunder Fang"),
    MOVE_ICE_FANG("Ice Fang"),
    MOVE_FIRE_FANG("Fire Fang"),
    MOVE_SHADOW_SNEAK("Shadow Sneak"),
    MOVE_MUD_BOMB("Mud Bomb"),
    MOVE_PSYCHO_CUT("Psycho Cut"),
    MOVE_ZEN_HEADBUTT("Zen Headbutt"),
    MOVE_MIRROR_SHOT("Mirror Shot"),
    MOVE_FLASH_CANNON("Flash Cannon"),
    MOVE_ROCK_CLIMB("Rock Climb"),
    MOVE_DEFOG("Defog"),
    MOVE_TRICK_ROOM("Trick Room"),
    MOVE_DRACO_METEOR("Draco Meteor"),
    MOVE_DISCHARGE("Discharge"),
    MOVE_LAVA_PLUME("Lava Plume"),
    MOVE_LEAF_STORM("Leaf Storm"),
    MOVE_POWER_WHIP("Power Whip"),
    MOVE_ROCK_WRECKER("Rock Wrecker"),
    MOVE_CROSS_POISON("Cross Poison"),
    MOVE_GUNK_SHOT("Gunk Shot"),
    MOVE_IRON_HEAD("Iron Head"),
    MOVE_MAGNET_BOMB("Magnet Bomb"),
    MOVE_STONE_EDGE("Stone Edge"),
    MOVE_CAPTIVATE("Captivate"),
    MOVE_STEALTH_ROCK("Stealth Rock"),
    MOVE_GRASS_KNOT("Grass Knot"),
    MOVE_CHATTER("Chatter"),
    MOVE_JUDGMENT("Judgment"),
    MOVE_BUG_BITE("Bug Bite"),
    MOVE_CHARGE_BEAM("Charge Beam"),
    MOVE_WOOD_HAMMER("Wood Hammer"),
    MOVE_AQUA_JET("Aqua Jet"),
    MOVE_ATTACK_ORDER("Attack Order"),
    MOVE_DEFEND_ORDER("Defend Order"),
    MOVE_HEAL_ORDER("Heal Order"),
    MOVE_HEAD_SMASH("Head Smash"),
    MOVE_DOUBLE_HIT("Double Hit"),
    MOVE_ROAR_OF_TIME("Roar of Time"),
    MOVE_SPACIAL_REND("Spacial Rend"),
    MOVE_LUNAR_DANCE("Lunar Dance"),
    MOVE_CRUSH_GRIP("Crush Grip"),
    MOVE_MAGMA_STORM("Magma Storm"),
    MOVE_DARK_VOID("Dark Void"),
    MOVE_SEED_FLARE("Seed Flare"),
    MOVE_OMINOUS_WIND("Ominous Wind"),
    MOVE_SHADOW_FORCE("Shadow Force"),
    MOVE_HONE_CLAWS("Hone Claws"),
    MOVE_WIDE_GUARD("Wide Guard"),
    MOVE_GUARD_SPLIT("Guard Split"),
    MOVE_POWER_SPLIT("Power Split"),
    MOVE_WONDER_ROOM("Wonder Room"),
    MOVE_PSYSHOCK("Psyshock"),
    MOVE_VENOSHOCK("Venoshock"),
    MOVE_AUTOTOMIZE("Autotomize"),
    MOVE_RAGE_POWDER("Rage Powder"),
    MOVE_TELEKINESIS("Telekinesis"),
    MOVE_MAGIC_ROOM("Magic Room"),
    MOVE_SMACK_DOWN("Smack Down"),
    MOVE_STORM_THROW("Storm Throw"),
    MOVE_FLAME_BURST("Flame Burst"),
    MOVE_SLUDGE_WAVE("Sludge Wave"),
    MOVE_QUIVER_DANCE("Quiver Dance"),
    MOVE_HEAVY_SLAM("Heavy Slam"),
    MOVE_SYNCHRONOISE("Synchronoise"),
    MOVE_ELECTRO_BALL("Electro Ball"),
    MOVE_SOAK("Soak"),
    MOVE_FLAME_CHARGE("Flame Charge"),
    MOVE_COIL("Coil"),
    MOVE_LOW_SWEEP("Low Sweep"),
    MOVE_ACID_SPRAY("Acid Spray"),
    MOVE_FOUL_PLAY("Foul Play"),
    MOVE_SIMPLE_BEAM("Simple Beam"),
    MOVE_ENTRAINMENT("Entrainment"),
    MOVE_AFTER_YOU("After You"),
    MOVE_ROUND("Round"),
    MOVE_ECHOED_VOICE("Echoed Voice"),
    MOVE_CHIP_AWAY("Chip Away"),
    MOVE_CLEAR_SMOG("Clear Smog"),
    MOVE_STORED_POWER("Stored Power"),
    MOVE_QUICK_GUARD("Quick Guard"),
    MOVE_ALLY_SWITCH("Ally Switch"),
    MOVE_SCALD("Scald"),
    MOVE_SHELL_SMASH("Shell Smash"),
    MOVE_HEAL_PULSE("Heal Pulse"),
    MOVE_HEX("Hex"),
    MOVE_SKY_DROP("Sky Drop"),
    MOVE_SHIFT_GEAR("Shift Gear"),
    MOVE_CIRCLE_THROW("Circle Throw"),
    MOVE_INCINERATE("Incinerate"),
    MOVE_QUASH("Quash"),
    MOVE_ACROBATICS("Acrobatics"),
    MOVE_REFLECT_TYPE("Reflect Type"),
    MOVE_RETALIATE("Retaliate"),
    MOVE_FINAL_GAMBIT("Final Gambit"),
    MOVE_BESTOW("Bestow"),
    MOVE_INFERNO("Inferno"),
    MOVE_WATER_PLEDGE("Water Pledge"),
    MOVE_FIRE_PLEDGE("Fire Pledge"),
    MOVE_GRASS_PLEDGE("Grass Pledge"),
    MOVE_VOLT_SWITCH("Volt Switch"),
    MOVE_STRUGGLE_BUG("Struggle Bug"),
    MOVE_BULLDOZE("Bulldoze"),
    MOVE_FROST_BREATH("Frost Breath"),
    MOVE_DRAGON_TAIL("Dragon Tail"),
    MOVE_WORK_UP("Work Up"),
    MOVE_ELECTROWEB("Electroweb"),
    MOVE_WILD_CHARGE("Wild Charge"),
    MOVE_DRILL_RUN("Drill Run"),
    MOVE_DUAL_CHOP("Dual Chop"),
    MOVE_HEART_STAMP("Heart Stamp"),
    MOVE_HORN_LEECH("Horn Leech"),
    MOVE_SACRED_SWORD("Sacred Sword"),
    MOVE_RAZOR_SHELL("Razor Shell"),
    MOVE_HEAT_CRASH("Heat Crash"),
    MOVE_LEAF_TORNADO("Leaf Tornado"),
    MOVE_STEAMROLLER("Steamroller"),
    MOVE_COTTON_GUARD("Cotton Guard"),
    MOVE_NIGHT_DAZE("Night Daze"),
    MOVE_PSYSTRIKE("Psystrike"),
    MOVE_TAIL_SLAP("Tail Slap"),
    MOVE_HURRICANE("Hurricane"),
    MOVE_HEAD_CHARGE("Head Charge"),
    MOVE_GEAR_GRIND("Gear Grind"),
    MOVE_SEARING_SHOT("Searing Shot"),
    MOVE_TECHNO_BLAST("Techno Blast"),
    MOVE_RELIC_SONG("Relic Song"),
    MOVE_SECRET_SWORD("Secret Sword"),
    MOVE_GLACIATE("Glaciate"),
    MOVE_BOLT_STRIKE("Bolt Strike"),
    MOVE_BLUE_FLARE("Blue Flare"),
    MOVE_FIERY_DANCE("Fiery Dance"),
    MOVE_FREEZE_SHOCK("Freeze Shock"),
    MOVE_ICE_BURN("Ice Burn"),
    MOVE_SNARL("Snarl"),
    MOVE_ICICLE_CRASH("Icicle Crash"),
    MOVE_VCREATE("V-create"),
    MOVE_FUSION_FLARE("Fusion Flare"),
    MOVE_FUSION_BOLT("Fusion Bolt");
    
    private final String moveNameFriendly;
    
    WBPMLLevelUpMoveNames (String moveNameFriendly) {
        this.moveNameFriendly = moveNameFriendly;
    }
    
    public String getMoveNameFriendly() {
        return moveNameFriendly;
    }
}
