<<<<<<< HEAD
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
=======
>>>>>>> 687ba7a2a4bb0efb135b3f8e32f3f1163e8d32f2
package ctrmap.editor.gui.editors.gen5.level.entities;

import ctrmap.editor.gui.editors.common.AbstractToolbarEditor;
import ctrmap.editor.gui.editors.common.tools.AbstractTool;
<<<<<<< HEAD
import ctrmap.editor.gui.editors.gen5.level.VLevelEditor;
import ctrmap.editor.gui.editors.gen5.level.tools.VInitScriptsTool;
import ctrmap.editor.gui.editors.gen5.level.tools.VScriptAssistantTool;
import java.util.List;
import xstandard.util.ArraysEx;

public class VInitScriptEditor extends javax.swing.JPanel implements AbstractToolbarEditor {

    private VLevelEditor editors;

    private VInitScriptsTool tool;

    public VInitScriptEditor() {
        initComponents();
        this.editors = editors;
        tool = new VInitScriptsTool(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSpinner10 = new javax.swing.JSpinner();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Run Condition", "Script ID"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry"));

        jLabel18.setText("Run Condition");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Script ID");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox6, 0, 123, Short.MAX_VALUE)
                            .addComponent(jSpinner7)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Static (Condition-Based)", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Work ID", "Expected Value", "Script ID"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry"));

        jLabel21.setText("Script ID");

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel22.setText("Expected Value");

        jLabel23.setText("Work ID");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner10, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jSpinner9)
                            .addComponent(jSpinner8))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dynamic (Variable-Based)", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<AbstractTool> getTools() {
            return ArraysEx.asList(tool);
=======
import ctrmap.editor.gui.editors.gen5.level.tools.VInitScriptsTool;
import ctrmap.formats.pokemon.gen5.zone.entities.VZoneInitScriptDispatcher;
import ctrmap.formats.pokemon.gen5.zone.entities.VZoneInitScriptDispatcher.DynamicInitScript;
import ctrmap.formats.pokemon.gen5.zone.entities.VZoneInitScriptDispatcher.StaticInitScript;
import ctrmap.formats.pokemon.gen5.zone.entities.VZoneInitScriptDispatcher.WkCmpEntry;
import ctrmap.missioncontrol_ntr.field.debug.VZoneDebugger;
import ctrmap.missioncontrol_ntr.field.structs.VZone;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import xstandard.util.ArraysEx;

public class VInitScriptEditor extends JPanel implements AbstractToolbarEditor, VZoneDebugger {

    private VInitScriptsTool tool;
    private VZoneInitScriptDispatcher dispatcher;
    private boolean updating = false;

    // Static tab
    private DefaultTableModel staticTableModel;
    private JTable staticTable;
    private JSpinner staticTagSpinner, staticScrIDSpinner;
    private JButton staticAddBtn, staticRemoveBtn;

    // Dynamic tab
    private DefaultTableModel dynTableModel;
    private JTable dynTable;
    private JSpinner dynWkIDSpinner, dynRefValSpinner, dynScrIDSpinner;
    private JButton dynAddBtn, dynRemoveBtn;

    public VInitScriptEditor() {
        tool = new VInitScriptsTool(this);
        initLayout();
        initListeners();
    }

    private void initLayout() {
        setLayout(new BorderLayout(4, 4));

        JTabbedPane tabs = new JTabbedPane();

        // ===== Static (Condition-Based) Tab =====
        JPanel staticPanel = new JPanel(new BorderLayout(4, 4));
        staticPanel.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));

        staticTableModel = new DefaultTableModel(new String[]{"Tag (Condition)", "Script ID"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        staticTable = new JTable(staticTableModel);
        staticTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        staticPanel.add(new JScrollPane(staticTable), BorderLayout.CENTER);

        // Entry editor
        JPanel staticEntryPanel = new JPanel(new GridBagLayout());
        staticEntryPanel.setBorder(BorderFactory.createTitledBorder("Entry"));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(2, 4, 2, 4);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0;
        staticEntryPanel.add(new JLabel("Tag (Condition)"), gbc);
        gbc.gridx = 1; gbc.weightx = 1.0;
        staticTagSpinner = new JSpinner(new SpinnerNumberModel(2, 2, 65535, 1));
        staticEntryPanel.add(staticTagSpinner, gbc);

        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0;
        staticEntryPanel.add(new JLabel("Script ID"), gbc);
        gbc.gridx = 1; gbc.weightx = 1.0;
        staticScrIDSpinner = new JSpinner(new SpinnerNumberModel(0, 0, 65535, 1));
        staticEntryPanel.add(staticScrIDSpinner, gbc);

        JPanel staticBtnPanel = new JPanel(new GridLayout(1, 2, 4, 0));
        staticAddBtn = new JButton("Add");
        staticRemoveBtn = new JButton("Remove");
        staticBtnPanel.add(staticAddBtn);
        staticBtnPanel.add(staticRemoveBtn);

        gbc.gridx = 0; gbc.gridy = 2; gbc.gridwidth = 2;
        staticEntryPanel.add(staticBtnPanel, gbc);

        staticPanel.add(staticEntryPanel, BorderLayout.SOUTH);
        tabs.addTab("Static (Condition-Based)", staticPanel);

        // ===== Dynamic (Variable-Based) Tab =====
        JPanel dynPanel = new JPanel(new BorderLayout(4, 4));
        dynPanel.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));

        dynTableModel = new DefaultTableModel(new String[]{"Work ID", "Expected Value", "Script ID"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        dynTable = new JTable(dynTableModel);
        dynTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        dynPanel.add(new JScrollPane(dynTable), BorderLayout.CENTER);

        // Entry editor
        JPanel dynEntryPanel = new JPanel(new GridBagLayout());
        dynEntryPanel.setBorder(BorderFactory.createTitledBorder("Entry"));
        GridBagConstraints gbc2 = new GridBagConstraints();
        gbc2.insets = new Insets(2, 4, 2, 4);
        gbc2.fill = GridBagConstraints.HORIZONTAL;

        gbc2.gridx = 0; gbc2.gridy = 0; gbc2.weightx = 0;
        dynEntryPanel.add(new JLabel("Work ID"), gbc2);
        gbc2.gridx = 1; gbc2.weightx = 1.0;
        dynWkIDSpinner = new JSpinner(new SpinnerNumberModel(1, 1, 65535, 1));
        dynEntryPanel.add(dynWkIDSpinner, gbc2);

        gbc2.gridx = 0; gbc2.gridy = 1; gbc2.weightx = 0;
        dynEntryPanel.add(new JLabel("Expected Value"), gbc2);
        gbc2.gridx = 1; gbc2.weightx = 1.0;
        dynRefValSpinner = new JSpinner(new SpinnerNumberModel(0, 0, 65535, 1));
        dynEntryPanel.add(dynRefValSpinner, gbc2);

        gbc2.gridx = 0; gbc2.gridy = 2; gbc2.weightx = 0;
        dynEntryPanel.add(new JLabel("Script ID"), gbc2);
        gbc2.gridx = 1; gbc2.weightx = 1.0;
        dynScrIDSpinner = new JSpinner(new SpinnerNumberModel(0, 0, 65535, 1));
        dynEntryPanel.add(dynScrIDSpinner, gbc2);

        JPanel dynBtnPanel = new JPanel(new GridLayout(1, 2, 4, 0));
        dynAddBtn = new JButton("Add");
        dynRemoveBtn = new JButton("Remove");
        dynBtnPanel.add(dynAddBtn);
        dynBtnPanel.add(dynRemoveBtn);

        gbc2.gridx = 0; gbc2.gridy = 3; gbc2.gridwidth = 2;
        dynEntryPanel.add(dynBtnPanel, gbc2);

        dynPanel.add(dynEntryPanel, BorderLayout.SOUTH);
        tabs.addTab("Dynamic (Variable-Based)", dynPanel);

        add(tabs, BorderLayout.CENTER);
    }

    private void initListeners() {
        // Static table selection → populate entry fields
        staticTable.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting() || updating || dispatcher == null) return;
            int sel = staticTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.staticScripts.size()) {
                updating = true;
                StaticInitScript s = dispatcher.staticScripts.get(sel);
                staticTagSpinner.setValue(s.tag);
                staticScrIDSpinner.setValue(s.SCRID);
                updating = false;
            }
        });

        // Static spinner changes update selected row live
        staticTagSpinner.addChangeListener(e -> {
            if (updating || dispatcher == null) return;
            int sel = staticTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.staticScripts.size()) {
                updating = true;
                dispatcher.staticScripts.get(sel).tag = (int) staticTagSpinner.getValue();
                refreshStaticTable();
                staticTable.setRowSelectionInterval(sel, sel);
                updating = false;
            }
        });
        staticScrIDSpinner.addChangeListener(e -> {
            if (updating || dispatcher == null) return;
            int sel = staticTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.staticScripts.size()) {
                updating = true;
                dispatcher.staticScripts.get(sel).SCRID = (int) staticScrIDSpinner.getValue();
                refreshStaticTable();
                staticTable.setRowSelectionInterval(sel, sel);
                updating = false;
            }
        });

        // Static Add — new entry with defaults, then select it for editing
        staticAddBtn.addActionListener(e -> {
            if (dispatcher != null) {
                updating = true;
                StaticInitScript s = new StaticInitScript();
                s.tag = 2;
                s.SCRID = 0;
                dispatcher.staticScripts.add(s);
                refreshStaticTable();
                int idx = dispatcher.staticScripts.size() - 1;
                staticTable.setRowSelectionInterval(idx, idx);
                staticTagSpinner.setValue(s.tag);
                staticScrIDSpinner.setValue(s.SCRID);
                updating = false;
            }
        });

        // Static Remove
        staticRemoveBtn.addActionListener(e -> {
            if (dispatcher != null) {
                int sel = staticTable.getSelectedRow();
                if (sel >= 0 && sel < dispatcher.staticScripts.size()) {
                    updating = true;
                    dispatcher.staticScripts.remove(sel);
                    refreshStaticTable();
                    updating = false;
                }
            }
        });

        // Dynamic table selection → populate entry fields
        dynTable.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting() || updating || dispatcher == null || dispatcher.dynScr == null) return;
            int sel = dynTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.dynScr.branches.size()) {
                updating = true;
                WkCmpEntry entry = dispatcher.dynScr.branches.get(sel);
                dynWkIDSpinner.setValue(entry.wkId);
                dynRefValSpinner.setValue(entry.refVal);
                dynScrIDSpinner.setValue(entry.SCRID);
                updating = false;
            }
        });

        // Dynamic spinner changes update selected row live
        dynWkIDSpinner.addChangeListener(e -> {
            if (updating || dispatcher == null || dispatcher.dynScr == null) return;
            int sel = dynTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.dynScr.branches.size()) {
                updating = true;
                dispatcher.dynScr.branches.get(sel).wkId = (int) dynWkIDSpinner.getValue();
                refreshDynTable();
                dynTable.setRowSelectionInterval(sel, sel);
                updating = false;
            }
        });
        dynRefValSpinner.addChangeListener(e -> {
            if (updating || dispatcher == null || dispatcher.dynScr == null) return;
            int sel = dynTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.dynScr.branches.size()) {
                updating = true;
                dispatcher.dynScr.branches.get(sel).refVal = (int) dynRefValSpinner.getValue();
                refreshDynTable();
                dynTable.setRowSelectionInterval(sel, sel);
                updating = false;
            }
        });
        dynScrIDSpinner.addChangeListener(e -> {
            if (updating || dispatcher == null || dispatcher.dynScr == null) return;
            int sel = dynTable.getSelectedRow();
            if (sel >= 0 && sel < dispatcher.dynScr.branches.size()) {
                updating = true;
                dispatcher.dynScr.branches.get(sel).SCRID = (int) dynScrIDSpinner.getValue();
                refreshDynTable();
                dynTable.setRowSelectionInterval(sel, sel);
                updating = false;
            }
        });

        // Dynamic Add — new entry with defaults, then select it for editing
        dynAddBtn.addActionListener(e -> {
            if (dispatcher != null) {
                updating = true;
                if (dispatcher.dynScr == null) {
                    dispatcher.dynScr = new DynamicInitScript();
                }
                WkCmpEntry entry = new WkCmpEntry();
                entry.wkId = 1;
                entry.refVal = 0;
                entry.SCRID = 0;
                dispatcher.dynScr.branches.add(entry);
                refreshDynTable();
                int idx = dispatcher.dynScr.branches.size() - 1;
                dynTable.setRowSelectionInterval(idx, idx);
                dynWkIDSpinner.setValue(entry.wkId);
                dynRefValSpinner.setValue(entry.refVal);
                dynScrIDSpinner.setValue(entry.SCRID);
                updating = false;
            }
        });

        // Dynamic Remove
        dynRemoveBtn.addActionListener(e -> {
            if (dispatcher != null && dispatcher.dynScr != null) {
                int sel = dynTable.getSelectedRow();
                if (sel >= 0 && sel < dispatcher.dynScr.branches.size()) {
                    updating = true;
                    dispatcher.dynScr.branches.remove(sel);
                    refreshDynTable();
                    updating = false;
                }
            }
        });
    }

    // ===== Data Binding =====

    @Override
    public void loadZone(VZone z) {
        if (z != null && z.initScrUnused != null) {
            this.dispatcher = z.initScrUnused;
        } else {
            this.dispatcher = null;
        }
        refreshStaticTable();
        refreshDynTable();
    }

    private void refreshStaticTable() {
        staticTableModel.setRowCount(0);
        if (dispatcher != null) {
            for (StaticInitScript s : dispatcher.staticScripts) {
                staticTableModel.addRow(new Object[]{s.tag, s.SCRID});
            }
        }
    }

    private void refreshDynTable() {
        dynTableModel.setRowCount(0);
        if (dispatcher != null && dispatcher.dynScr != null) {
            for (WkCmpEntry e : dispatcher.dynScr.branches) {
                dynTableModel.addRow(new Object[]{e.wkId, e.refVal, e.SCRID});
            }
        }
    }

    // ===== AbstractToolbarEditor =====

    @Override
    public List<AbstractTool> getTools() {
        return ArraysEx.asList(tool);
>>>>>>> 687ba7a2a4bb0efb135b3f8e32f3f1163e8d32f2
    }
}
