<<<<<<< HEAD
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ctrmap.editor.gui.editors.gen5.battle.encounters;

import ctrmap.formats.pokemon.gen5.battle.encounters.WBEncEntry;
import ctrmap.formats.pokemon.text.TextFile;
import java.awt.event.ActionEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author platinum
 */
public class VWildEncounterSlot extends javax.swing.JPanel {
    public VWildEncounterSlot() {
        initComponents();
    }
    
    public VWildEncounterSlot(WBEncEntry Entry, TextFile PkmnNames) {
        this();
        
        // Populate combobox for species.
        this.speciesComboBox.setModel(new DefaultComboBoxModel(PkmnNames.getFriendlyLinesArray()));
        this.speciesComboBox.addActionListener((ActionEvent ae) -> {
            short SelIndex = (short) this.speciesComboBox.getSelectedIndex();
            if (Entry != null && SelIndex >= 0) {
                Entry.SetSpecies(SelIndex);
            }
        });
        this.formSpinner.addChangeListener((ChangeEvent c) -> {
            short SelVal = (short) this.formSpinner.getValue();
            if (Entry != null && SelVal >= 0) {
                Entry.SetForm(SelVal);
            }
        });
        this.minLevelSpinner.addChangeListener((ChangeEvent c) -> {
            byte SelVal = (byte) this.minLevelSpinner.getValue();
            if (Entry != null && SelVal >= 0) {
                Entry.SetMinLevel(SelVal);
            }
        });
        this.maxLevelSpinner.addChangeListener((ChangeEvent c) -> {
            byte SelVal = (byte) this.maxLevelSpinner.getValue();
            if (Entry != null && SelVal >= 0) {
                Entry.SetMaxLevel(SelVal);
            }
        });
        
        UI_Update(Entry);
    }
    
    void UI_Update(WBEncEntry Entry) {
        if (Entry != null) {
            this.speciesComboBox.setSelectedIndex(Entry.GetSpecies());
            this.formSpinner.setValue(Entry.GetForm());
            this.minLevelSpinner.setValue((byte)Entry.GetMinLevel());
            this.maxLevelSpinner.setValue((byte)Entry.GetMaxLevel());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chancePercentageLabel = new javax.swing.JLabel();
        speciesComboBox = new javax.swing.JComboBox<>();
        formSpinner = new javax.swing.JSpinner();
        minLevelSpinner = new javax.swing.JSpinner();
        maxLevelSpinner = new javax.swing.JSpinner();

        chancePercentageLabel.setText("jLabel1");

        speciesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        formSpinner.setModel(new javax.swing.SpinnerNumberModel((short)0, null, null, (short)1));

        minLevelSpinner.setModel(new javax.swing.SpinnerNumberModel((byte)0, null, null, (byte)1));

        maxLevelSpinner.setModel(new javax.swing.SpinnerNumberModel((byte)0, null, null, (byte)1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chancePercentageLabel)
                .addGap(18, 18, 18)
                .addComponent(speciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minLevelSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxLevelSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chancePercentageLabel)
                    .addComponent(speciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chancePercentageLabel;
    private javax.swing.JSpinner formSpinner;
    private javax.swing.JSpinner maxLevelSpinner;
    private javax.swing.JSpinner minLevelSpinner;
    private javax.swing.JComboBox<String> speciesComboBox;
    // End of variables declaration//GEN-END:variables
=======
package ctrmap.editor.gui.editors.gen5.battle.encounters;

import ctrmap.formats.pokemon.gen5.battle.encounters.WBEncEntry;
import ctrmap.formats.pokemon.gen5.battle.encounters.WBEnc;
import ctrmap.formats.pokemon.text.TextFile;
import java.awt.*;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import java.awt.event.ActionEvent;

public class VWildEncounterSlot extends JPanel {

    static final int[] GRASS_RATES = {20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1};
    static final int[] SURF_RATES  = {60, 30, 5, 4, 1};
    static final int[] FISH_RATES  = {60, 30, 5, 4, 1};

    private WBEncEntry entry;
    private JComboBox<String> speciesCombo;
    private JSpinner formSpinner, minLevelSpinner, maxLevelSpinner;
    private JLabel rateLabel;

    public VWildEncounterSlot(WBEncEntry entry, TextFile pkmnNames, int slotIndex, WBEnc.WBEncType encType) {
        this.entry = entry;
        setLayout(new FlowLayout(FlowLayout.LEFT, 4, 1));
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));

        // Determine rate
        int rate = 0;
        int[] rates = null;
        switch (encType) {
            case GRASS:
            case GRASS_DOUBLE:
            case GRASS_RARE:
                rates = GRASS_RATES;
                break;
            case SURF:
            case SURF_RARE:
                rates = SURF_RATES;
                break;
            case FISH:
            case FISH_RARE:
                rates = FISH_RATES;
                break;
        }
        if (rates != null && slotIndex >= 0 && slotIndex < rates.length) {
            rate = rates[slotIndex];
        }

        // Rate label with color coding
        rateLabel = new JLabel(rate + "%", SwingConstants.RIGHT);
        rateLabel.setPreferredSize(new Dimension(40, 22));
        rateLabel.setFont(rateLabel.getFont().deriveFont(Font.BOLD));
        rateLabel.setOpaque(true);
        if (rate >= 10) {
            rateLabel.setBackground(new Color(144, 238, 144)); // green
        } else if (rate >= 4) {
            rateLabel.setBackground(new Color(255, 255, 150)); // yellow
        } else {
            rateLabel.setBackground(new Color(255, 180, 120)); // orange/red
        }
        add(rateLabel);

        // Species combo box
        speciesCombo = new JComboBox<>(pkmnNames.getFriendlyLinesArray());
        speciesCombo.setPreferredSize(new Dimension(180, 22));
        if (entry != null) {
            int dexNum = entry.GetDexNum();
            if (dexNum >= 0 && dexNum < speciesCombo.getItemCount()) {
                speciesCombo.setSelectedIndex(dexNum);
            }
        }
        speciesCombo.addActionListener((ActionEvent ae) -> {
            short selIndex = (short) speciesCombo.getSelectedIndex();
            if (this.entry != null && selIndex >= 0) {
                this.entry.SetDexNum(selIndex);
            }
        });
        add(speciesCombo);

        // Form label + spinner
        add(new JLabel("Form"));
        formSpinner = new JSpinner(new SpinnerNumberModel(0, 0, 255, 1));
        formSpinner.setPreferredSize(new Dimension(50, 22));
        if (entry != null) {
            formSpinner.setValue((int) entry.GetFormNum());
        }
        formSpinner.addChangeListener((ChangeEvent c) -> {
            short selVal = ((Number) formSpinner.getValue()).shortValue();
            if (this.entry != null && selVal >= 0) {
                this.entry.SetFormNum(selVal);
            }
        });
        add(formSpinner);

        // Level labels + spinners
        add(new JLabel("Lv"));
        minLevelSpinner = new JSpinner(new SpinnerNumberModel(0, 0, 100, 1));
        minLevelSpinner.setPreferredSize(new Dimension(45, 22));
        if (entry != null) {
            minLevelSpinner.setValue((int) entry.GetMinLevel());
        }
        minLevelSpinner.addChangeListener((ChangeEvent c) -> {
            byte selVal = ((Number) minLevelSpinner.getValue()).byteValue();
            if (this.entry != null && selVal >= 0) {
                this.entry.SetMinLevel(selVal);
            }
        });
        add(minLevelSpinner);

        add(new JLabel("-"));

        maxLevelSpinner = new JSpinner(new SpinnerNumberModel(0, 0, 100, 1));
        maxLevelSpinner.setPreferredSize(new Dimension(45, 22));
        if (entry != null) {
            maxLevelSpinner.setValue((int) entry.GetMaxLevel());
        }
        maxLevelSpinner.addChangeListener((ChangeEvent c) -> {
            byte selVal = ((Number) maxLevelSpinner.getValue()).byteValue();
            if (this.entry != null && selVal >= 0) {
                this.entry.SetMaxLevel(selVal);
            }
        });
        add(maxLevelSpinner);
    }
>>>>>>> 687ba7a2a4bb0efb135b3f8e32f3f1163e8d32f2
}
