/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ctrmap.editor.gui.editors.gen5.battle.pokemon;

import ctrmap.editor.CTRMap;
import ctrmap.editor.gui.editors.util.SystemTextLUT;
import ctrmap.editor.gui.editors.util.TextSingleton;
import ctrmap.formats.pokemon.gen5.pml.WBPMLLearnsets;
import ctrmap.formats.pokemon.gen5.pml.WBPMLLevelUpMove;
import ctrmap.formats.pokemon.text.TextFile;
import ctrmap.missioncontrol_ntr.fs.NARCRef;
import ctrmap.missioncontrol_ntr.fs.NTRGameFS;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hibiki
 */
public class VLearnsetEditor extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VLearnsetEditor.class.getName());
    
    private CTRMap Instance;
    private TextFile MoveNames;
    private ArrayList<WBPMLLevelUpMove> listLearnset;
    
    /**
     * Creates new form VLearnsetEditor
     */
    private VLearnsetEditor() {
        initComponents();
    }
    
    public VLearnsetEditor(WBPMLLearnsets learnset) throws IOException {
        initComponents();
        
        DefaultListModel<String> jList1Model = new DefaultListModel<>();
        
        if (learnset != null) {
            listLearnset = new ArrayList<WBPMLLevelUpMove>();
            
//            for (int Index = 1; Index < this.MoveNames.getLineCount(); ++Index) {
//                this.jCBLearnsetMoves.addItem(this.MoveNames.getLine(Index));
//            }
            
            for (int Index = 0; Index < learnset.GetLearnsetSize(); ++Index) {
                
                WBPMLLevelUpMove move = new WBPMLLevelUpMove(
                        learnset.GetLevelUpMove(Index).GetMoveName(),
                        learnset.GetLevelUpMove(Index).GetLearnLevel()
                );
                
                listLearnset.add(move);
                
                System.out.println(listLearnset.get(Index).GetMoveName());
            }

            jList1.setModel(jList1Model);
            
//            for (int Index = 0; Index < listLearnset.size(); ++Index) {
//                System.out.println(listLearnset.get(Index).GetMoveName() + ", Lv" + listLearnset.get(Index).GetLearnLevel());
//                if (listLearnset.get(Index).GetLearnLevel() != 65535) {
//                    String moveName = MoveFriendlyName(listLearnset.get(Index).GetMoveName());
//                    jList1Model.addElement(moveName + ", Lv" + listLearnset.get(Index).GetLearnLevel());
//                }
//            }
        } else {
            System.out.println("The learnset is empty!");
        }
        
        setVisible(true);
    }

    
    
    NTRGameFS FS() {
        return Instance.getMissionControl(ctrmap.missioncontrol_ntr.VLaunchpad.class).fs;
    }
    
    TextFile LoadTextFile(String File) {
        return TextSingleton.Load(FS(), NARCRef.MSGDATA_SYSTEM, SystemTextLUT.get(File));
    }
    
    private void LoadMoveNameTextArchive() {
        this.MoveNames = LoadTextFile("Moves");
    }
    
//    public String MoveFriendlyName(String moveName) {
//        String MoveFriendlyName = "";
//        
//        for (int Index = 0; Index < MoveNames.getLineCount(); Index++) {
//            int NameIndex = 0;
//            
//            if (moveName.equals("MOVE_" + MoveNames.getLine(NameIndex).toUpperCase())) {
//                MoveFriendlyName = MoveNames.getLine(NameIndex);
//                continue;
//            } else {
//                NameIndex++;
//            }
//        }
//        
//        return MoveFriendlyName;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel15 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jCBLearnsetMoves = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jSpinnerLearnsetLevel6 = new javax.swing.JSpinner();
        jBtnLearnsetAdd = new javax.swing.JButton();
        jBtnLearnsetRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learnset Editor");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Entry"));

        jLabel47.setText("Move");

        jLabel48.setText("Level");

        jBtnLearnsetAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrmap/resources/personaleditor/icon_add.png"))); // NOI18N
        jBtnLearnsetAdd.setText("Add");
        jBtnLearnsetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLearnsetAddActionPerformed(evt);
            }
        });

        jBtnLearnsetRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrmap/resources/personaleditor/icon_remove.png"))); // NOI18N
        jBtnLearnsetRemove.setText("Remove");
        jBtnLearnsetRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLearnsetRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnLearnsetAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnLearnsetRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jCBLearnsetMoves, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerLearnsetLevel6)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBLearnsetMoves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerLearnsetLevel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLearnsetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLearnsetRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLearnsetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLearnsetAddActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnLearnsetAddActionPerformed

    private void jBtnLearnsetRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLearnsetRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLearnsetRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VLearnsetEditor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLearnsetAdd;
    private javax.swing.JButton jBtnLearnsetRemove;
    private javax.swing.JComboBox<String> jCBLearnsetMoves;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerLearnsetLevel6;
    // End of variables declaration//GEN-END:variables
}
