/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ctrmap.editor.gui.editors.gen5.battle.pokemon;

import ctrmap.editor.CTRMap;
import ctrmap.editor.gui.editors.common.AbstractTabbedEditor;
import ctrmap.editor.gui.editors.gen5.battle.trainer.VTrainerComponent;
import ctrmap.editor.gui.editors.gen5.battle.trainer.VTrainerDataBinding;
import ctrmap.editor.gui.editors.gen5.battle.trainer.VTrainerEditor;
import ctrmap.editor.gui.editors.util.SystemTextLUT;
import ctrmap.editor.gui.editors.util.TextSingleton;
import ctrmap.editor.gui.editors.util.UserEnumHandler;
import ctrmap.editor.system.workspace.CTRMapProject;
import ctrmap.editor.system.workspace.UserData;
import ctrmap.formats.common.GameInfo;
import ctrmap.formats.common.GameInfoListener;
import ctrmap.formats.pokemon.gen5.battle.trainer.WBTrainerData;
import ctrmap.formats.pokemon.gen5.battle.trainer.WBTrainerPoke;
import ctrmap.formats.pokemon.gen5.pml.WBPMLPersonal;
import ctrmap.formats.pokemon.text.GenVMessageHandler;
import ctrmap.formats.pokemon.text.TextFile;
import ctrmap.missioncontrol_base.debug.IMCDebugger;
import ctrmap.missioncontrol_ntr.fs.NARCRef;
import ctrmap.missioncontrol_ntr.fs.NTRGameFS;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import xstandard.formats.yaml.Yaml;
import xstandard.formats.yaml.YamlNode;
import xstandard.formats.yaml.YamlReflectUtil;
import xstandard.fs.FSFile;

public class VPokemonEditor extends javax.swing.JPanel implements AbstractTabbedEditor {
    private CTRMap Instance;
    private TextFile PkmnNames, AbilNames, MoveNames, MoveDescs, ItemNames, ItemDescs, Learnsets, Evolutions, Types;
    
    private enum parseType {
            TYPE_NORMAL,
            TYPE_FIGHTING,
            TYPE_FLYING,
            TYPE_POISON,
            TYPE_GROUND,
            TYPE_ROCK,
            TYPE_BUG,
            TYPE_GHOST,
            TYPE_STEEL,
            TYPE_FIRE,
            TYPE_WATER,
            TYPE_GRASS,
            TYPE_ELECTRIC,
            TYPE_PSYCHIC,
            TYPE_ICE,
            TYPE_DRAGON,
            TYPE_DARK,
            TYPE_FAIRY
        }
    
    private List<WBPMLPersonal> Pokemon;
    
    public VPokemonEditor(CTRMap Instance) {
        initComponents();
        this.Pokemon = new ArrayList<>();
        this.Instance = Instance;
        
        LoadAllTextArchives();
        
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        for (int Index = 0; Index < this.PkmnNames.getLineCount(); ++Index) {
             cbm.addElement(this.PkmnNames.getLine(Index));
        }
        this.speciesSelector.getCB().setModel(cbm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileLoadPanel = new javax.swing.JPanel();
        btnOpenScrInIDE22 = new javax.swing.JButton();
        btnAddPersonalData = new javax.swing.JButton();
        speciesSelector = new xstandard.gui.components.combobox.ComboBoxAndSpinner();
        jSpeciesMetadata = new javax.swing.JTabbedPane();

        fileLoadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Species"));

        btnOpenScrInIDE22.setText("Open Species");
        btnOpenScrInIDE22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenScrInIDE22ActionPerformed(evt);
            }
        });

        btnAddPersonalData.setText("+");
        btnAddPersonalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonalDataActionPerformed(evt);
            }
        });

        speciesSelector.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        speciesSelector.setMaximumRowCount(35);

        javax.swing.GroupLayout fileLoadPanelLayout = new javax.swing.GroupLayout(fileLoadPanel);
        fileLoadPanel.setLayout(fileLoadPanelLayout);
        fileLoadPanelLayout.setHorizontalGroup(
            fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(speciesSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPersonalData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenScrInIDE22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        fileLoadPanelLayout.setVerticalGroup(
            fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadPanelLayout.createSequentialGroup()
                .addGroup(fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpenScrInIDE22)
                        .addComponent(btnAddPersonalData))
                    .addComponent(speciesSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpeciesMetadata)
                    .addComponent(fileLoadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpeciesMetadata, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    NTRGameFS FS() {
        return Instance.getMissionControl(ctrmap.missioncontrol_ntr.VLaunchpad.class).fs;
    }
    
    TextFile LoadTextFile(String File) {
        return TextSingleton.Load(FS(), NARCRef.MSGDATA_SYSTEM, SystemTextLUT.get(File));
    }
    
    private void LoadAllTextArchives() {
        this.PkmnNames = LoadTextFile("Pokemon");
        this.MoveNames = LoadTextFile("Moves");
        this.Types = LoadTextFile("Types");
    }
    
//    private WBPMLPersonal GetCurrentSpecies() {
//        //Load current species.
//        int Index = speciesSelector.getValueSpinner();
//        if (Index < 0 || Index > FS().NARCGetDataMax(NARCRef.PML_PERSONAL)) {
//            return null;
//        }
//        return Pokemon.get(Index);
//    }
    
    public WBPMLPersonal LoadEntryViaYml(Yaml yml) throws Exception {
        // Deserialize the YML into some bindings.
        if (yml.root.children.size() != 1) {
            return null;
        }
        VPokemonPersonalDataBinding personalYml = YamlReflectUtil.deserialize(yml.root.children.get(0), VPokemonPersonalDataBinding.class);
        
        WBPMLPersonal personalData = new WBPMLPersonal();
        
        personalData.SetBaseHP(personalYml.baseHP);
        personalData.SetBaseAttack(personalYml.baseAttack);
        personalData.SetBaseDefense(personalYml.baseDefense);
        personalData.SetBaseSpAttack(personalYml.baseSpAttack);
        personalData.SetBaseSpDefense(personalYml.baseSpDefense);
        personalData.SetBaseSpeed(personalYml.baseSpeed);
        
        try {
            parseType type = parseType.valueOf(personalYml.primaryType);
            int typeIndex = type.ordinal();
            
            personalData.SetPrimaryType(typeIndex);
        } catch (IllegalArgumentException e) {
            System.out.println("Could not parse type string with enum");
        }
        
        try {
            parseType type = parseType.valueOf(personalYml.secondaryType);
            int typeIndex = type.ordinal();
            
            personalData.SetSecondaryType(typeIndex);
        } catch (IllegalArgumentException e) {
            System.out.println("Could not parse type string with enum");
        }
        
        personalData.SetCaptureRate(personalYml.captureRate);
        personalData.SetEvYield(personalYml.evYield);
        personalData.SetWildItem50(personalYml.wildItem50);
        personalData.SetWildItem5(personalYml.wildItem5);
        personalData.SetWildItem1(personalYml.wildItem1);
        personalData.SetGenderProbability(personalYml.genderProbability);
        personalData.SetEggHappiness(personalYml.eggHappiness);
        personalData.SetBaseHappiness(personalYml.baseHappiness);
        personalData.SetExperienceGroup(personalYml.experienceGroup);
        personalData.SetEggGroup1(personalYml.eggGroup1);
        personalData.SetEggGroup2(personalYml.eggGroup2);
        personalData.SetPrimaryAbility(personalYml.primaryAbility);
        personalData.SetSecondaryAbility(personalYml.secondaryAbility);
        personalData.SetHiddenAbility(personalYml.hiddenAbility);
        personalData.SetEscapeRate(personalYml.escapeRate);
        personalData.SetFormDataOffSet(personalYml.formDataOffset);
        personalData.SetFormSpriteOffSet(personalYml.formSpriteOffset);
        personalData.SetFormCount(personalYml.formCount);
        personalData.SetColor(personalYml.color);
        personalData.SetBaseExperience(personalYml.baseExperience);
        personalData.SetHeightCm(personalYml.heightCm);
        personalData.SetWeightCg(personalYml.weightCg);
        personalData.SetTechnicalOrHiddenMachine1(personalYml.tmhm1);
        personalData.SetTechnicalOrHiddenMachine2(personalYml.tmhm2);
        personalData.SetTechnicalOrHiddenMachine3(personalYml.tmhm3);
        personalData.SetTechnicalOrHiddenMachine4(personalYml.tmhm4);
        personalData.SetTypeTutors(personalYml.typeTutors);
        personalData.SetSpecialTutors(personalYml.specialTutors);
        
        return personalData;
    }
        
    private void btnOpenScrInIDE22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenScrInIDE22ActionPerformed
        // Check if the user directory exists.
        FSFile pml_user_directory = Instance.getProject().userData.getUserDataDir(UserData.UsrDirectory.PML_PERSONAL);
        int personalIndex = speciesSelector.getValueSpinner();
        String yaml_name = String.format("%d.yml", personalIndex);
        if (pml_user_directory.exists() && pml_user_directory.getChildCount() > 0) {
            FSFile personal_yaml = pml_user_directory.getChild(yaml_name);
            if (personal_yaml.exists()) {
                WBPMLPersonal pml_personal;
                try {
                    pml_personal = this.LoadEntryViaYml(new Yaml(personal_yaml));
                    String name = PkmnNames.getLine(personalIndex);
                    this.jSpeciesMetadata.add(String.format("%d - %s", personalIndex, this.PkmnNames.getLine(personalIndex)), new VPokemonEditorComponent(this.Instance, pml_personal, personalIndex, name));
                } catch (Exception ex) {
                    Logger.getLogger(VTrainerEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("Did not find YAML");
            } 
        }
    }//GEN-LAST:event_btnOpenScrInIDE22ActionPerformed

    private void btnAddPersonalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonalDataActionPerformed

    }//GEN-LAST:event_btnAddPersonalDataActionPerformed

    @Override
    public String getTabName() {
        return "Pokémon Editor";
    }

    @Override
    public boolean isGameSupported(GameInfo game) {
        return game.isGenV();
    }

    @Override
    public boolean isDebugOnly() {
        return AbstractTabbedEditor.super.isDebugOnly(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public boolean isSharedInstance() {
        return AbstractTabbedEditor.super.isSharedInstance(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public List<GameInfoListener> getGameInfoListeners() {
        return AbstractTabbedEditor.super.getGameInfoListeners(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public Collection<? extends IMCDebugger> getExtraDebuggers() {
        return AbstractTabbedEditor.super.getExtraDebuggers(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void prepareForSave() {
        AbstractTabbedEditor.super.prepareForSave(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public boolean store(boolean dialog) {
        return AbstractTabbedEditor.super.store(dialog); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void handleGlobalEvent(String eventId, Object... params) {
        AbstractTabbedEditor.super.handleGlobalEvent(eventId, params); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void onProjectLoaded(CTRMapProject proj) {
        AbstractTabbedEditor.super.onProjectLoaded(proj); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void onProjectUnloaded(CTRMapProject proj) {
        AbstractTabbedEditor.super.onProjectUnloaded(proj); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPersonalData;
    private javax.swing.JButton btnOpenScrInIDE22;
    private javax.swing.JPanel fileLoadPanel;
    private javax.swing.JTabbedPane jSpeciesMetadata;
    private xstandard.gui.components.combobox.ComboBoxAndSpinner speciesSelector;
    // End of variables declaration//GEN-END:variables
}
