/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ctrmap.editor.gui.editors.gen5.battle.pokemon;

import ctrmap.editor.CTRMap;
import ctrmap.editor.gui.editors.common.AbstractTabbedEditor;
import ctrmap.editor.gui.editors.gen5.battle.trainer.VTrainerComponent;
import ctrmap.editor.gui.editors.gen5.battle.trainer.VTrainerDataBinding;
import ctrmap.editor.gui.editors.gen5.battle.trainer.VTrainerEditor;
import ctrmap.editor.gui.editors.util.UserEnumHandler;
import ctrmap.editor.system.workspace.CTRMapProject;
import ctrmap.editor.system.workspace.UserData;
import ctrmap.formats.common.GameInfo;
import ctrmap.formats.common.GameInfoListener;
import ctrmap.formats.pokemon.gen5.battle.trainer.WBTrainerData;
import ctrmap.formats.pokemon.gen5.battle.trainer.WBTrainerPoke;
import ctrmap.formats.pokemon.gen5.pml.WBPMLPersonal;
import ctrmap.missioncontrol_base.debug.IMCDebugger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import xstandard.formats.yaml.Yaml;
import xstandard.formats.yaml.YamlNode;
import xstandard.formats.yaml.YamlReflectUtil;
import xstandard.fs.FSFile;

public class VPokemonEditor extends javax.swing.JPanel implements AbstractTabbedEditor {
    private CTRMap Instance;
    public VPokemonEditor() {
        initComponents();
    }

    public VPokemonEditor(CTRMap Instance) {
        initComponents();
        this.Instance = Instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileLoadPanel = new javax.swing.JPanel();
        btnOpenScrInIDE22 = new javax.swing.JButton();
        btnAddZoneData = new javax.swing.JButton();
        trainerSelector = new xstandard.gui.components.combobox.ComboBoxAndSpinner();
        jTrainerMetadata = new javax.swing.JTabbedPane();

        fileLoadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Trainer"));

        btnOpenScrInIDE22.setText("Open Trainer");
        btnOpenScrInIDE22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenScrInIDE22ActionPerformed(evt);
            }
        });

        btnAddZoneData.setText("+");
        btnAddZoneData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddZoneDataActionPerformed(evt);
            }
        });

        trainerSelector.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        trainerSelector.setMaximumRowCount(35);

        javax.swing.GroupLayout fileLoadPanelLayout = new javax.swing.GroupLayout(fileLoadPanel);
        fileLoadPanel.setLayout(fileLoadPanelLayout);
        fileLoadPanelLayout.setHorizontalGroup(
            fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddZoneData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenScrInIDE22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        fileLoadPanelLayout.setVerticalGroup(
            fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadPanelLayout.createSequentialGroup()
                .addGroup(fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fileLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpenScrInIDE22)
                        .addComponent(btnAddZoneData))
                    .addComponent(trainerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTrainerMetadata)
                    .addComponent(fileLoadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTrainerMetadata, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public WBPMLPersonal LoadEntryViaYml(Yaml yml) throws Exception {
        // Deserialize the YML into some bindings.
        if (yml.root.children.size() != 1) {
            return null;
        }
        VPokemonPersonalDataBinding personalYml = YamlReflectUtil.deserialize(yml.root.children.get(0), VPokemonPersonalDataBinding.class);
        
        WBPMLPersonal trData = new WBPMLPersonal();
        return trData;
    }
        
    private void btnOpenScrInIDE22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenScrInIDE22ActionPerformed
        // Check if the user directory exists.
        FSFile pml_user_directory = Instance.getProject().userData.getUserDataDir(UserData.UsrDirectory.PML_PERSONAL);
        int personalIndex = trainerSelector.getValueSpinner();
        String yaml_name = String.format("%d.yml", personalIndex);
        if (pml_user_directory.exists() && pml_user_directory.getChildCount() > 0) {
            FSFile personal_yaml = pml_user_directory.getChild(yaml_name);
            if (personal_yaml.exists()) {
                WBPMLPersonal pml_personal;
                try {
                    pml_personal = this.LoadEntryViaYml(new Yaml(personal_yaml));
                } catch (Exception ex) {
                    Logger.getLogger(VTrainerEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("Did not find YAML");
            } 
        }
    }//GEN-LAST:event_btnOpenScrInIDE22ActionPerformed

    private void btnAddZoneDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddZoneDataActionPerformed

    }//GEN-LAST:event_btnAddZoneDataActionPerformed

    @Override
    public String getTabName() {
        return "Pokémon Editor";
    }

    @Override
    public boolean isGameSupported(GameInfo game) {
        return game.isGenV();
    }

    @Override
    public boolean isDebugOnly() {
        return AbstractTabbedEditor.super.isDebugOnly(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public boolean isSharedInstance() {
        return AbstractTabbedEditor.super.isSharedInstance(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public List<GameInfoListener> getGameInfoListeners() {
        return AbstractTabbedEditor.super.getGameInfoListeners(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public Collection<? extends IMCDebugger> getExtraDebuggers() {
        return AbstractTabbedEditor.super.getExtraDebuggers(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void prepareForSave() {
        AbstractTabbedEditor.super.prepareForSave(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public boolean store(boolean dialog) {
        return AbstractTabbedEditor.super.store(dialog); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void handleGlobalEvent(String eventId, Object... params) {
        AbstractTabbedEditor.super.handleGlobalEvent(eventId, params); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void onProjectLoaded(CTRMapProject proj) {
        AbstractTabbedEditor.super.onProjectLoaded(proj); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void onProjectUnloaded(CTRMapProject proj) {
        AbstractTabbedEditor.super.onProjectUnloaded(proj); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddZoneData;
    private javax.swing.JButton btnOpenScrInIDE22;
    private javax.swing.JPanel fileLoadPanel;
    private javax.swing.JTabbedPane jTrainerMetadata;
    private xstandard.gui.components.combobox.ComboBoxAndSpinner trainerSelector;
    // End of variables declaration//GEN-END:variables
}
